"""empty message

Revision ID: 41469c2aab11
Revises: 
Create Date: 2017-03-13 21:16:43.634842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41469c2aab11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profile',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.CHAR(length=80), nullable=True),
    sa.Column('biography', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profile')
    # ### end Alembic commands ###
