"""empty message

Revision ID: aab9f094db09
Revises: 5eddd7717ba6
Create Date: 2017-03-13 22:56:30.460313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aab9f094db09'
down_revision = '5eddd7717ba6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('date', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'date')
    # ### end Alembic commands ###
